<?php View::content() ?>
<div class="span12 pagination-centered">
    <?php echo Html::img('logos/loter.jpg') ?>
</div>
<table class="table table-bordered">
    <tr>
        <td width="33%" align="center"><p><strong>El Sistema Nacional de Acreditación de Colombia</strong></p>
            <p align="justify"><small>El Sistema Nacional de Acreditación de Colombia fue creado por la Ley 30 de 1992 con el objetivo fundamental de garantizar a la sociedad que las instituciones que hacen parte del Sistema cumplen los más altos requisitos de calidad y realizan sus propósitos y objetivos.</small></p>
            <p align="justify"><small>La Acreditación es un testimonio que da el Estado sobre la calidad de un   programa o institución.</small></p>
        </td>
        <td width="33%" align="center"><p><strong>Realizar Encuesta</strong></p>
            <a href="javascript:cerrar();Abrir_ventana('/ucalidad/calidad/educacion/login.php');"> <strong>Acreditacion de Alta Calidad</strong></a>
            <h6 href="javascript:cerrar();Abrir_ventana('/ucalidad/calidad/psicologia/login2.php');"><strong>Autoevaluacion de Programas</strong></h6>
            <p align="justify"><small>La Universidad Mariana  se encuentra siguiendo un proceso de acreditaci&oacute;n de alta calidad en el cual, la informaci&oacute;n que suministre ser&aacute; de gran importancia. Lea con atenci&oacute;n cada una de las preguntas y responda  todas con sinceridad y objetividad. La universidad Mariana agradece su colaboraci&oacute;n.</small></p>
        </td>
        <td width="33%" align="center"><h6 href="javascript:cerrar();Abrir_ventana('/ucalidad/calidad/psicologia/login1.php');"><strong>Realizar Ponderacion</strong></h6>
            <p align="justify"><small>Cada participante asigna de manera individual el puntaje para cada característica. Una vez que hayan hecho lo mismo, cada  participante dirá en voz alta el puntaje y expresará las razones del mismo.La ponderación de cada una de las características resulta del promedio de los puntajes asignados por los diferentes participantes, aunque lo deseable sería llegar al consenso.</small></p>
        </td>
    </tr>
</table>