<div id='info'>    
    <h3>Acreditación de Alta Calidad</h3>

El Sistema Nacional de Acreditación, creado por la Ley 30 de 1992, inició su implantación con la acreditación de programas académicos, en este momento ya se adelantan procesos de acreditación institucional.

Con la implantación de este Sistema, se garantizará a la sociedad que los programas académicos y las instituciones de educación superior que pertenecen a él cumplen con los más altos requisitos de calidad y realizan los propósitos y objetivos que han declarado tener.
<h3>Acreditación de Instituciones</h3>

La Acreditación Institucional correrá paralela a la acreditación de programas en un esfuerzo compartido entre la institución, la comunidad académica y el CNA. El propósito es mantener la vigencia de ambas y su mutua fundamentación y refuerzo.
<h3>Acreditación de Programas</h3>

El Sistema Nacional de Acreditación, creado por la Ley 30 de 1992, inició su implantación con la acreditación de programas académicos, está en plena vigencia y se viene consolidando con la voluntad y compromiso de las instituciones de educación superior que han decidido rendir cuentas sobre la calidad del servicio que prestan.
<h3>Evaluación de Estándares de Calidad</h3>

Ademas de la Acreditación de Alta Calidad el Ministerio de Educación Nacional ha encargado al Consejo Nacional de Acreditación de los procesos de Acreditación Previa de Programas de Educación, y Registro Calificado de programas del área de Ingeniería y del área de la Salud.

A diferencia de los procesos de Acreditación de Alta Calidad , que son voluntarios, estos procesos son de carácter obligatorio y tienen connotaciones de inspección y vigilancia.

</div>
