<?php View::content() ?>
<div><h3>Facultad de Ciencias Contables y Administrativas</h3></div>
<table class="table table-bordered">
    <tr>
        <td><strong>Realizar Encuesta</strong></td>
        <td><strong>Administrar Información</strong></td>
    </tr>
    <tr class="success">
        <td><strong><?php echo Html::link('listarprogramas/contaduria', 'Contaduria Pública') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/ingSistemas/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
    <tr>
        <td><strong><?php echo Html::link('listarprogramas/negocios', 'Administración de Negocios Internacionales') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/ingAmbiental/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
</table>