<?php View::content() ?>
<div><h3>Facultad de Humanidades y Ciencias Sociales</h3></div>
<table class="table table-bordered">
    <tr>
        <td><strong>Realizar Encuesta</strong></td>
        <td><strong>Administrar Información</strong></td>
    </tr>
    <tr class="success">
        <td><strong><?php echo Html::link('listarprogramas/trabajoSocial', 'Trabajo Social') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/ingSistemas/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
    <tr>
        <td><strong><?php echo Html::link('listarprogramas/psicologia', 'Psicología') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/ingAmbiental/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
    <tr class="success">
        <td><strong><?php echo Html::link('listarprogramas/derecho', 'Derecho') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/ingProcesos/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
    <tr>
        <td><strong><?php echo Html::link('listarprogramas/comunicacionSocial', 'Comunicación Social - Periodismo') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/autoElectronica/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
</table>