<?php View::content() ?>
<div><h3>Facultad de Ingeniería</h3></div>
<table class="table table-bordered">
    <tr>
        <td><strong>Realizar Encuesta</strong></td>
        <td><strong>Administrar Información</strong></td>
    </tr>
    <tr class="success">
        <td><strong><?php echo Html::link('listarprogramas/sistemas', 'Ingeniería de Sistemas') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/ingSistemas/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
    <tr>
        <td><strong><?php echo Html::link('listarprogramas/ambiental', 'Ingeniería Ambiental') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/ingAmbiental/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
    <tr class="success">
        <td><strong><?php echo Html::link('listarprogramas/procesos', 'Ingeniería de Procesos') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/ingProcesos/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
    <tr>
        <td><strong><?php echo Html::link('listarprogramas/electronica', 'Automatización Electrónica') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/autoElectronica/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
</table>