<?php View::content() ?>
<div><h3>Facultad de Postgrados y Relaciones Internacionales</h3></div>
<table class="table table-bordered">
    <tr>
        <td><strong>Realizar Encuesta</strong></td>
        <td><strong>Administrar Información</strong></td>
    </tr>
    <tr class="success">
        <td><strong><?php echo Html::link('listarprogramas/postgrados', 'Postgrados') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/ingSistemas/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
</table>