<?php View::content() ?>
<div><h3>Facultad de Ciencias de la Salud</h3></div>
<table class="table table-bordered">
    <tr>
        <td><strong>Realizar Encuesta</strong></td>
        <td><strong>Administrar Información</strong></td>
    </tr>
    <tr class="success">
        <td><strong><?php echo Html::link('listarprogramas/enfermeria', 'Enfermería') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/ingSistemas/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
    <tr>
        <td><strong><?php echo Html::link('listarprogramas/fisioterapia', 'Fisioterapia') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/ingAmbiental/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
    <tr class="success">
        <td><strong><?php echo Html::link('listarprogramas/terapiaOcupacional', 'Terapia Ocuapacional') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/ingProcesos/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
    <tr>
        <td><strong><?php echo Html::link('listarprogramas/regencia', 'Tecnología en Regencia de Farmacia') ?></strong></td>
        <td><strong><a href="/ucalidad/calidad/autoElectronica/menu1/">Entrar a la Plataforma</a></strong></td>
    </tr>
</table>