<h2>Registro de Preguntas.</h2>
<? echo Form::open() ?>

<? echo Form::label('Cuestionario', 'cuestionario'); ?>
<? echo Form::dbSelect('pregunta.cue_id', 'nombre'); ?><!-- modelo . campo relacionado -->

<? echo Form::label('Pregunta: ', 'pregunta'); ?>
<? echo Form::textarea('pregunta.pregunta'); ?>

<? echo Form::label('Titulo', 'titulo') ?>
<? echo Form::text('pregunta.titulo') ?>

<? echo Form::label('Unica', 'unica') ?>
Si: <? echo Form::radio("pregunta.unica", '1', NULL, TRUE); ?>
No: <? echo Form::radio("pregunta.unica", '0'); ?>

<h2>Campos de las Pregunta.</h2>
<a href="#" id="addMore">Otro campo</a> <? echo Form::submit('Enviar') ?>
<div id="miscampos">
    <div id="micampo">
        <p>__________________________________________________________________</p>
        <? echo Form::label('Campo', 'nombre') ?>
        <? echo Form::text('campopregunta.nombrecampo'); ?>

        <? echo Form::label('Tipo', 'tipo'); ?>
        <? echo Form::dbSelect('campopregunta.tipocampo_id', 'nombre'); ?>
        <p>__________________________________________________________________</p>
    </div>
</div>
<br>

<? echo Form::close() ?>
<? echo View::content() ?>