<h2>Registro de Preguntas.</h2>
<? echo Form::open() ?>


<? echo Form::label('Cuestionario', 'cuestionario'); ?>
<? echo Form::dbSelect('pregunta.cue_id', 'nombre'); ?><!-- modelo . campo relacionado -->

<? echo Form::label('Pregunta: ', 'pregunta'); ?>
<? echo Form::textarea('pregunta.pregunta'); ?>

<? echo Form::label('Titulo', 'titulo') ?>
<? echo Form::text('pregunta.titulo') ?>

<? echo Form::label('Unica Respuesta', 'unica') ?>
Si: <? echo Form::radio("pregunta.unica", '1', NULL, TRUE); ?>
No: <? echo Form::radio("pregunta.unica", '0'); ?>

<h2>Campos de las Pregunta.</h2>
<a href="#" id="addButton">Agregar Campo</a>
<a href="#" id="removeButton">Eliminar Campo</a>
<a href="#" id="getButtonValue">Dar Campos</a>
<? echo Form::submit('Enviar') ?>
<div id="TextBoxesGroup">
    <div id="TextBoxDiv1">
        <p>__________________________________________________________________</p>
        <label for="nombre">Campo1</label>
        <input id="campo1" type="text" name="campo1" value="">
        <label for="tipo">Tipo1</label>
        <select id="tipocampo1" name="tipocampo1">
            <option value="1">int</option>
            <option value="2">text</option>
        </select>
        <p>__________________________________________________________________</p>
    </div>
</div>
<br>
<div id="contador"></div>

<? echo Form::close() ?>
<? echo View::content() ?>